apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    deployment.kubernetes.io/desired-replicas: "1"
    deployment.kubernetes.io/max-replicas: "2"
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-03-11T12:17:55Z"
  generation: 1
  labels:
    app: dobrobot
    pod-template-hash: 7dc6cb674d
  name: dobrobot-7dc6cb674d
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: Deployment
    name: dobrobot
    uid: 563e63d3-6392-11ea-a88e-42010a8000ab
  resourceVersion: "1100431"
  selfLink: /apis/apps/v1/namespaces/default/replicasets/dobrobot-7dc6cb674d
  uid: 563fad71-6392-11ea-89d0-42010a8000e4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dobrobot
      pod-template-hash: 7dc6cb674d
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dobrobot
        pod-template-hash: 7dc6cb674d
    spec:
      containers:
      - image: gcr.io/GKE_PROJECT/IMAGE:TAG
        imagePullPolicy: Always
        name: dobrobot
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  fullyLabeledReplicas: 1
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1

        

