apiVersion: apps/v1beta1
kind: Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dobrobot
  template:
    spec:
      containers:
      - image: gcr.io/GKE_PROJECT/IMAGE:TAG
        imagePullPolicy: Always
        name: dobrobot
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

        
